server:
  port: 8080
  servlet:
    contextPath: /${spring.application.name}/v1
spring:
  application:
    name: mssivimss-ayuda-gtos-fune
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  main:
    allow-circular-references: true

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate: error

endpoints:
  mod-catalogos: ''
  ms-reportes: ''
  url-nssa: http://tspi-stage.imss.gob.mx/agf-web-service/AyudaGastosFunerales?WSDL
  agf-asegurados: http://certificacion.service.agf.ctirss.imss.gob.mx/AyudaGastosFunerales/obtenerAGFAsegurado
  agf-pensionado: http://certificacion.service.agf.ctirss.imss.gob.mx/AyudaGastosFunerales/obtenerAGFPensionado

jwt:
  secretkey-flujo: funcionamuybien
  secretkey-dominios: funcionamuybiendominio
  expiration-milliseconds: 360

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

resilience4j.circuitbreaker:
  circuitBreakerAspectOrder: 1
  instances:
    msflujo:
      automaticTransitionFromOpenToHalfOpenEnabled: 'true'
      failureRateThreshold: 5
      slidingWindowType: COUNT_BASED
      event-consumer-buffer-size: '10'
      registerHealthIndicator: 'true'
      waitDurationInOpenState: 5s
      permittedNumberOfCallsInHalfOpenState: 5
      slidingWindowSize: '5'
resilience4j.retry:
  retryAspectOrder: 2
  instances:
    msflujo:
      maxAttempts: 5
      waitDuration: 5s
resilience4j.timelimiter:
  timeLimiterAspectOrder: 3
  instances:
    msflujo:
      timeout-duration: 5s

formato_fecha: '%d/%m/%Y %H:%i:%s'
ruta-log: ''
