
package com.imss.sivimss.registroagf.service.nssa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AyudaGastosFunerales", targetNamespace = "http://certificacion.service.agf.ctirss.imss.gob.mx/", wsdlLocation = "http://172.16.168.92:8013/agf-web-service/AyudaGastosFunerales?WSDL")
public class AyudaGastosFunerales_Service
    extends Service
{

    private final static URL AYUDAGASTOSFUNERALES_WSDL_LOCATION;
    private final static WebServiceException AYUDAGASTOSFUNERALES_EXCEPTION;
    private final static QName AYUDAGASTOSFUNERALES_QNAME = new QName("http://certificacion.service.agf.ctirss.imss.gob.mx/", "AyudaGastosFunerales");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.168.92:8013/agf-web-service/AyudaGastosFunerales?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AYUDAGASTOSFUNERALES_WSDL_LOCATION = url;
        AYUDAGASTOSFUNERALES_EXCEPTION = e;
    }

    public AyudaGastosFunerales_Service() {
        super(__getWsdlLocation(), AYUDAGASTOSFUNERALES_QNAME);
    }

    public AyudaGastosFunerales_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AYUDAGASTOSFUNERALES_QNAME, features);
    }

    public AyudaGastosFunerales_Service(URL wsdlLocation) {
        super(wsdlLocation, AYUDAGASTOSFUNERALES_QNAME);
    }

    public AyudaGastosFunerales_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AYUDAGASTOSFUNERALES_QNAME, features);
    }

    public AyudaGastosFunerales_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AyudaGastosFunerales_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AyudaGastosFunerales
     */
    @WebEndpoint(name = "AyudaGastosFuneralesSOAP")
    public AyudaGastosFunerales getAyudaGastosFuneralesSOAP() {
        return super.getPort(new QName("http://certificacion.service.agf.ctirss.imss.gob.mx/", "AyudaGastosFuneralesSOAP"), AyudaGastosFunerales.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AyudaGastosFunerales
     */
    @WebEndpoint(name = "AyudaGastosFuneralesSOAP")
    public AyudaGastosFunerales getAyudaGastosFuneralesSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://certificacion.service.agf.ctirss.imss.gob.mx/", "AyudaGastosFuneralesSOAP"), AyudaGastosFunerales.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AYUDAGASTOSFUNERALES_EXCEPTION!= null) {
            throw AYUDAGASTOSFUNERALES_EXCEPTION;
        }
        return AYUDAGASTOSFUNERALES_WSDL_LOCATION;
    }

}
